born(jan, 20,3,1977).
born(jeroen, 2,2,1992).
born(joris, 17,3,1995).
born(jelle, 1,1,2004).
born(jesus, 24,12,2000).
born(joop, 30,4,1989).
born(jannecke, 17,3,1993).
born(jaap, 16,11,1995).

OUT PUT 
?- born(A,B,C,D).
A = jan,
B = 20,
C = 3,
D = 1977 
Unknown action: \ (h for help)
Action? ;
A = jeroen,
B = C, C = 2,
D = 1992 ;
A = joris,
B = 17,
C = 3,
D = 1995 ;
A = jelle,
B = C, C = 1,
D = 2004 ;
A = jesus,
B = 24,
C = 12,
D = 2000 
